image:
  repository: ghcr.io/sba25431/catalog
  tag: 3b7be7da7c4b1d398bcf818c8b9c98881988f601
postgresql:
  image:
    tag: latest
  auth:
    database: books
    username: books
    password: books
    postgresPassword: books
