image:
  repository: ghcr.io/sba25431/catalog
  tag: fc80486051402174f3a96e9a49f6229553632401
postgresql:
  image:
    tag: latest
  auth:
    database: books
    username: books
    password: books
    postgresPassword: books
