name: run test suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/install-dependencies

      - name: Run Pytest
        run: uv run pytest

  migrations-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/install-dependencies

      - name: Check missing migrations
        run: uv run manage.py makemigrations --check

  runmigrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/install-dependencies
      - name: Run migrations
        run: uv run manage.py migrate